import { PropertyType, Amenity } from "@prisma/client";
import type { SeedPropertyTemplate } from "../types.js";
import { pickImages } from "../images.js";

export const kyivProperties: SeedPropertyTemplate[] = [
  {
    title: "Modern Studio in Podil",
    description:
      "A stylish studio apartment in the heart of Podil, Kyiv's most vibrant neighbourhood. Floor-to-ceiling windows with views of the Dnipro, a fully equipped kitchen and a fast Wi-Fi connection make it perfect for remote work or a relaxing city break.",
    type: PropertyType.APARTMENT,
    city: "Kyiv",
    country: "Ukraine",
    district: "Podil",
    street: "Kontraktova Square",
    houseNumber: "4",
    latitude: 50.4636,
    longitude: 30.5187,
    pricePerNight: 28,
    maxGuests: 2,
    amenities: [Amenity.WIFI, Amenity.AIR_CONDITIONING, Amenity.KITCHEN, Amenity.WASHER],
    images: pickImages("minimalistModern", 5, 0),
    ownerEmail: "owner@demo.com",
    createdMonthsAgo: 14,
  },
  {
    title: "Spacious 2BR Apartment near Khreshchatyk",
    description:
      "A generous two-bedroom apartment just two minutes' walk from Kyiv's main boulevard. Classic Ukrainian interior blended with modern amenities: a projector screen, coffee machine and a soaking tub. Ideal for couples or small families.",
    type: PropertyType.APARTMENT,
    city: "Kyiv",
    country: "Ukraine",
    district: "Shevchenkivskyi",
    street: "Shevchenka Blvd",
    houseNumber: "12",
    apartment: "7",
    latitude: 50.4459,
    longitude: 30.5177,
    pricePerNight: 50,
    maxGuests: 4,
    amenities: [
      Amenity.WIFI,
      Amenity.KITCHEN,
      Amenity.WASHER,
      Amenity.PROJECTOR,
      Amenity.BATHTUB,
      Amenity.GYM,
    ],
    images: pickImages("cityApartment", 5, 0),
    ownerEmail: "owner2@demo.com",
    createdMonthsAgo: 20,
  },
  {
    title: "Cosy Room in Historic Pechersk",
    description:
      "A quiet private room in a shared apartment in Pechersk, a short metro ride from Lavra monastery and the main business district. Great natural light, a comfy bed and a private bathroom.",
    type: PropertyType.HOTEL_ROOM,
    city: "Kyiv",
    country: "Ukraine",
    district: "Pechersk",
    street: "Lypska St",
    houseNumber: "3",
    latitude: 50.4386,
    longitude: 30.5477,
    pricePerNight: 16,
    maxGuests: 1,
    infantsAllowed: false,
    amenities: [Amenity.WIFI, Amenity.AIR_CONDITIONING, Amenity.PRIVATE_BATHROOM],
    images: pickImages("compactRoom", 4, 0),
    ownerEmail: "owner@demo.com",
    createdMonthsAgo: 9,
  },
  {
    title: "Designer Loft on Vozdvizhenka",
    description:
      "A stunning loft apartment in one of Kyiv's most photogenic streets. Exposed brick walls, designer furniture, a record player and a rooftop terrace are waiting for you.",
    type: PropertyType.APARTMENT,
    city: "Kyiv",
    country: "Ukraine",
    district: "Podil",
    street: "Vozdvyzhenka St",
    houseNumber: "10",
    latitude: 50.4589,
    longitude: 30.5145,
    pricePerNight: 55,
    maxGuests: 3,
    infantsAllowed: false,
    amenities: [
      Amenity.WIFI,
      Amenity.KITCHEN,
      Amenity.ROOFTOP_TERRACE,
      Amenity.VINYL_RECORD_PLAYER,
      Amenity.COFFEE_MACHINE,
    ],
    images: pickImages("loftIndustrial", 5, 0),
    ownerEmail: "owner2@demo.com",
    createdMonthsAgo: 31,
  },
  {
    title: "Private House with Garden, Obolon",
    description:
      "A charming private house with a landscaped garden in the quiet Obolon district, on the left bank of the Dnipro. Three bedrooms, a barbecue area and a children's playground on site.",
    type: PropertyType.HOUSE,
    city: "Kyiv",
    country: "Ukraine",
    district: "Obolon",
    street: "Obolonska St",
    houseNumber: "22",
    latitude: 50.5044,
    longitude: 30.4986,
    pricePerNight: 95,
    maxGuests: 8,
    petsAllowed: true,
    amenities: [
      Amenity.WIFI,
      Amenity.PARKING,
      Amenity.GARDEN,
      Amenity.BBQ,
      Amenity.WASHER,
      Amenity.DISHWASHER,
      Amenity.KIDS_PLAY_AREA,
    ],
    images: pickImages("cabinCottage", 5, 0),
    ownerEmail: "owner@demo.com",
    createdMonthsAgo: 40,
  },
];
