import { PropertyType, Amenity } from "@prisma/client";
import type { SeedPropertyTemplate } from "../types.js";
import { pickImages } from "../images.js";

export const odesaProperties: SeedPropertyTemplate[] = [
  {
    title: "Sea View Apartment in Arcadia",
    description:
      "A bright apartment with panoramic views of the Black Sea, just 50 metres from Arcadia beach. Spend the day on the sand and the evening on your private balcony watching the sunset. Summer-ready: air-conditioned and with beach towels provided.",
    type: PropertyType.APARTMENT,
    city: "Odesa",
    country: "Ukraine",
    district: "Arcadia",
    street: "Genuezska St",
    houseNumber: "24",
    latitude: 46.4409,
    longitude: 30.7519,
    pricePerNight: 58,
    maxGuests: 3,
    amenities: [
      Amenity.WIFI,
      Amenity.AIR_CONDITIONING,
      Amenity.SEA_VIEW,
      Amenity.BALCONY,
      Amenity.BEACHFRONT,
      Amenity.KITCHEN,
    ],
    images: pickImages("beach", 5, 1),
    ownerEmail: "owner@demo.com",
    createdMonthsAgo: 16,
  },
  {
    title: "Heritage Apartment on Derybasivska",
    description:
      "Step back in time in this stunning apartment inside a 19th-century mansion on Odesa's most famous pedestrian street. Antique furniture, high ceilings and ornate moulding — combined with modern Wi-Fi and air conditioning.",
    type: PropertyType.APARTMENT,
    city: "Odesa",
    country: "Ukraine",
    district: "City Centre",
    street: "Derybasivska St",
    houseNumber: "16",
    latitude: 46.4814,
    longitude: 30.7397,
    pricePerNight: 52,
    maxGuests: 2,
    amenities: [Amenity.WIFI, Amenity.AIR_CONDITIONING, Amenity.HISTORIC_BUILDING, Amenity.CITY_CENTRE],
    images: pickImages("historicEuropean", 4, 5),
    ownerEmail: "owner2@demo.com",
    createdMonthsAgo: 22,
  },
  {
    title: "Beach House with Private Pool",
    description:
      "A luxurious private beach house with an infinity pool overlooking the sea. Four bedrooms, a fully equipped BBQ terrace and direct beach access via a private staircase. Ideal for groups or family holidays.",
    type: PropertyType.HOUSE,
    city: "Odesa",
    country: "Ukraine",
    district: "Fontanka",
    street: "Fontanska Rd",
    houseNumber: "40",
    latitude: 46.4219,
    longitude: 30.7714,
    pricePerNight: 120,
    maxGuests: 10,
    petsAllowed: true,
    amenities: [
      Amenity.WIFI,
      Amenity.POOL,
      Amenity.BBQ,
      Amenity.PARKING,
      Amenity.BEACHFRONT,
      Amenity.AIR_CONDITIONING,
      Amenity.SMART_TV,
    ],
    images: pickImages("villaPool", 6, 0),
    ownerEmail: "owner@demo.com",
    createdMonthsAgo: 45,
  },
];
