import {
  Accessibility,
  AlarmSmoke,
  Anchor,
  ArrowUpDown,
  Baby,
  Bath,
  Bike,
  Book,
  Building,
  Building2,
  Car,
  Castle,
  ChefHat,
  Coffee,
  CookingPot,
  Disc3,
  Dog,
  DoorOpen,
  Droplet,
  Droplets,
  Dumbbell,
  Fan,
  Flame,
  Landmark,
  Monitor,
  Palmtree,
  Projector,
  Sailboat,
  ShowerHead,
  Siren,
  Sun,
  Table2,
  Thermometer,
  Trees,
  Tv,
  Umbrella,
  Waves,
  WashingMachine,
  Wifi,
  Wind,
  type LucideIcon,
} from "lucide-react";
import type { Amenity } from "./properties";

/** Icon shown next to each amenity in the property detail page. */
export const AMENITY_ICONS: Record<Amenity, LucideIcon> = {
  WIFI: Wifi,
  AIR_CONDITIONING: Wind,
  HEATING: Thermometer,
  KITCHEN: CookingPot,
  WASHER: WashingMachine,
  DRYER: Fan,
  DISHWASHER: Droplets,
  PARKING: Car,
  POOL: Waves,
  GYM: Dumbbell,
  BALCONY: DoorOpen,
  TERRACE: Umbrella,
  ROOFTOP_TERRACE: Building2,
  GARDEN: Trees,
  BBQ: ChefHat,
  FIREPLACE: Flame,
  BATHTUB: Bath,
  PRIVATE_BATHROOM: ShowerHead,
  TV: Tv,
  SMART_TV: Monitor,
  COFFEE_MACHINE: Coffee,
  PROJECTOR: Projector,
  STANDING_DESK: Table2,
  ELEVATOR: ArrowUpDown,
  PET_FRIENDLY: Dog,
  WHEELCHAIR_ACCESSIBLE: Accessibility,
  SEA_VIEW: Waves,
  CITY_CENTRE: Landmark,
  BEACHFRONT: Palmtree,
  KIDS_PLAY_AREA: Baby,
  BIKE_INCLUDED: Bike,
  BIKE_RENTAL_NEARBY: Bike,
  COURTYARD: Building,
  CANAL_VIEW: Anchor,
  RIVER_VIEW: Droplet,
  SUN_DECK: Sun,
  KAYAK: Sailboat,
  HISTORIC_BUILDING: Castle,
  VINYL_RECORD_PLAYER: Disc3,
  BOOKS: Book,
  SMOKE_ALARM: AlarmSmoke,
  CARBON_MONOXIDE_ALARM: Siren,
};

export function amenityIcon(value: Amenity): LucideIcon {
  return AMENITY_ICONS[value];
}
