/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new user
         * @description Creates a new account. Passwords are scored with zxcvbn; anything
         *     below score 3 (common, short, predictable) is rejected even if it
         *     meets the 8-character minimum. `phoneNumber` is optional, but when
         *     supplied it must be a valid international number parseable by
         *     libphonenumber-js — typically E.164 with a leading `+` and country
         *     code. Reserved test ranges (e.g. US `555-01xx`) are rejected.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: email
                         * @description Lowercased and trimmed server-side.
                         * @example jane.doe@example.com
                         */
                        email: string;
                        /**
                         * @description Must pass zxcvbn strength check (score ≥ 3). Avoid common words, keyboard patterns, and personal info.
                         * @example Tr0ub4dor&3-Purge!
                         */
                        password: string;
                        /** @example Jane */
                        firstName: string;
                        /** @example Doe */
                        lastName: string;
                        /**
                         * @description Optional. International format (E.164 recommended). Validated with libphonenumber-js.
                         * @example +14155552671
                         */
                        phoneNumber?: string;
                    };
                };
            };
            responses: {
                /** @description User registered successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description Validation error (weak password, invalid phone, malformed email, etc.) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Registration conflict (typically email already in use; deliberately generic to avoid account enumeration) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Too many registration attempts (rate limited) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login and receive JWT tokens */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Login successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description Invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout and invalidate refresh token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logout successful */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh access token using HttpOnly cookie */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Token refreshed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            accessToken: string;
                        };
                    };
                };
                /** @description Refresh token missing or invalid */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/check-availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check property availability for a date range */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        propertyId: string;
                        /** Format: date-time */
                        checkIn: string;
                        /** Format: date-time */
                        checkOut: string;
                    };
                };
            };
            responses: {
                /** @description Availability result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            available: boolean;
                        };
                    };
                };
                400: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{propertyId}/blocked-dates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List blocked date ranges for a property */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    propertyId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Blocked date list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BlockedDates"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List bookings owned by current user (guest or host) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User booking list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["BookingListItem"][];
                            pagination: components["schemas"]["Pagination"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** Create new booking (guest) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        propertyId: string;
                        /** Format: date-time */
                        checkIn: string;
                        /** Format: date-time */
                        checkOut: string;
                        guests: number;
                    };
                };
            };
            responses: {
                /** @description Booking created (PENDING) */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BookingWithProperty"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                /** @description Date range conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/host": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List bookings on properties owned by current user (host) */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                    status?: "PENDING" | "CONFIRMED" | "CANCELLED" | "COMPLETED";
                    propertyId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Host booking list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["HostBooking"][];
                            pagination: components["schemas"]["Pagination"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get booking by id (guest or host only) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Booking detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BookingDetail"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Cancel booking (guest or host depending on state) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Booking cancelled */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            booking: components["schemas"]["Booking"] & {
                                property: components["schemas"]["Property"];
                            };
                            cancellation: {
                                refundPercent: number;
                                refundAmount: number;
                                hoursUntilCheckIn: number;
                                policy: {
                                    fullRefundAfterHours: number;
                                    partialRefundAfterHours: number;
                                    partialRefundPercent: number;
                                };
                            } | null;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update booking status (host confirm or system complete) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "CONFIRMED" | "COMPLETED";
                    };
                };
            };
            responses: {
                /** @description Booking status updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Booking"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/bookings/{id}/dates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Modify booking dates or guests (guest only, before check-in) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: date-time */
                        checkIn?: string;
                        /** Format: date-time */
                        checkOut?: string;
                        guests?: number;
                    };
                };
            };
            responses: {
                /** @description Booking dates updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BookingWithProperty"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description Date range conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/bookings/{id}/early-checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark booking as early checkout (guest) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Early checkout recorded */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Booking"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/favorites/ids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All favorited propertyIds for the current user (heart-state hydration) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Unpaginated list of favorited property ids */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ids: string[];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List current user's favorited properties */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated favorite list, newest first */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Favorite"][];
                            pagination: components["schemas"]["Pagination"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/favorites/{propertyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Favorite a property (idempotent) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    propertyId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Favorite created (or already existed) */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Favorite"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        /** Unfavorite a property (idempotent, no error if not favorited) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    propertyId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Favorite removed (or never existed) */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stripe webhook receiver (raw body, signature verified)
         * @description Mounted before JSON/auth middleware. Not for direct client use.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description Event processed (idempotent) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid signature or payload */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create payment record for a booking */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        bookingId: string;
                        /** @enum {string} */
                        provider: "STRIPE";
                        /** @default USD */
                        currency?: string;
                    };
                };
            };
            responses: {
                /** @description Payment created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Payment"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/intent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Stripe PaymentIntent for booking, returns client secret */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        bookingId: string;
                    };
                };
            };
            responses: {
                /** @description PaymentIntent client secret */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            clientSecret: string;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/payout-lifecycle/run-now": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger payout lifecycle job immediately (ADMIN only) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Job enqueued */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get payment by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Payment detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Payment"] & {
                            booking: components["schemas"]["Booking"] & {
                                property: components["schemas"]["Property"];
                            };
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/{id}/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Manual processing override (ADMIN, bypasses provider state check) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Payment marked processed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Payment"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/{id}/refund": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request refund for a payment (guest) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        reason?: string;
                    };
                };
            };
            responses: {
                /** @description Refund requested */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Payment"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/{id}/refund/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve refund request (ADMIN only) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Refund approved and issued */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Payment"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/{id}/refund/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject refund request (ADMIN only) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        reason?: string;
                    };
                };
            };
            responses: {
                /** @description Refund rejected */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Payment"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search properties with filters */
        get: {
            parameters: {
                query?: {
                    city?: string;
                    country?: string;
                    district?: string;
                    /** @description Filter to listings owned by this host */
                    ownerId?: string;
                    type?: "HOTEL_ROOM" | "APARTMENT" | "HOUSE" | "MEETING_ROOM";
                    /** @description CSV of Amenity enum values */
                    amenities?: string;
                    minPrice?: number;
                    maxPrice?: number;
                    maxGuests?: number;
                    /** @description true narrows to pet-friendly listings */
                    petsAllowed?: boolean;
                    /** @description true narrows to infant-suitable listings */
                    infantsAllowed?: boolean;
                    sort?: "price_asc" | "price_desc" | "newest";
                    page?: number;
                    limit?: number;
                    checkIn?: string;
                    checkOut?: string;
                    /** @description Bounding-box filter — provide all four of minLat/maxLat/minLng/maxLng together */
                    minLat?: number;
                    maxLat?: number;
                    minLng?: number;
                    maxLng?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated property list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["PropertyWithOwner"][];
                            pagination: components["schemas"]["Pagination"];
                        };
                    };
                };
                400: components["responses"]["ValidationError"];
            };
        };
        put?: never;
        /** Create new property listing */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        title: string;
                        description: string;
                        /** @enum {string} */
                        type: "HOTEL_ROOM" | "APARTMENT" | "HOUSE" | "MEETING_ROOM";
                        city: string;
                        country: string;
                        district?: string;
                        street: string;
                        houseNumber?: string;
                        apartment?: string;
                        latitude?: number;
                        longitude?: number;
                        pricePerNight: number;
                        maxGuests: number;
                        /** @example 15:00 */
                        checkInTime?: string;
                        /** @example 11:00 */
                        checkOutTime?: string;
                        amenities?: components["schemas"]["Amenity"][];
                        rawImagePaths?: string[];
                    };
                };
            };
            responses: {
                /** @description Property created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PropertyWithOwner"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List properties owned by current user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of owned properties */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Property"][];
                            pagination: components["schemas"]["Pagination"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties/map-markers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All matching map markers (no pagination) for the browse map */
        get: {
            parameters: {
                query?: {
                    city?: string;
                    country?: string;
                    district?: string;
                    ownerId?: string;
                    type?: "HOTEL_ROOM" | "APARTMENT" | "HOUSE" | "MEETING_ROOM";
                    /** @description CSV of Amenity enum values */
                    amenities?: string;
                    minPrice?: number;
                    maxPrice?: number;
                    maxGuests?: number;
                    petsAllowed?: boolean;
                    infantsAllowed?: boolean;
                    checkIn?: string;
                    checkOut?: string;
                    /** @description Bounding-box filter — provide all four of minLat/maxLat/minLng/maxLng together */
                    minLat?: number;
                    maxLat?: number;
                    minLng?: number;
                    maxLng?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Markers for every active listing matching the filters, capped at 500 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PropertyMapMarker"][];
                    };
                };
                400: components["responses"]["ValidationError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Location facets (country/city/district counts) for active listings */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Location tree, sorted alphabetically at every level */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LocationCountry"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties/address-suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Address autocomplete for the host form (English-normalized) */
        get: {
            parameters: {
                query: {
                    q: string;
                    limit?: number;
                    kind?: "street" | "city";
                    /** @description Prefer results from this country */
                    country?: string;
                    /** @description Prefer results from this city (street kind only) */
                    city?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Street- and house-level suggestions with coordinates */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AddressSuggestion"][];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get property by id (auth optional, reveals owner extras) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Property detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PropertyDetail"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Soft-delete property (owner only) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Property deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** Update property (owner only) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        title?: string;
                        description?: string;
                        /** @enum {string} */
                        type?: "HOTEL_ROOM" | "APARTMENT" | "HOUSE" | "MEETING_ROOM";
                        city?: string;
                        country?: string;
                        district?: string | null;
                        street?: string;
                        houseNumber?: string | null;
                        apartment?: string | null;
                        latitude?: number;
                        longitude?: number;
                        pricePerNight?: number;
                        maxGuests?: number;
                        /** @example 15:00 */
                        checkInTime?: string | null;
                        /** @example 11:00 */
                        checkOutTime?: string | null;
                        amenities?: components["schemas"]["Amenity"][];
                        images?: string[];
                    };
                };
            };
            responses: {
                /** @description Property updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Property"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/properties/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload raw property image files (owner only, pre-create) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        images: string[];
                    };
                };
            };
            responses: {
                /** @description Raw image paths saved, ready for rawImagePaths on create/update */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            paths: string[];
                        };
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties/{id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate property listing (owner only) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Property activated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Property"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deactivate property listing (owner only) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Property deactivated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Property"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/property/{propertyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List reviews for a property */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                    sort?: "recent" | "highest" | "lowest";
                    rating?: number;
                    hasHostReply?: boolean;
                };
                header?: never;
                path: {
                    propertyId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated review list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Review"][];
                            pagination: components["schemas"]["Pagination"];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/property/{propertyId}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregated review stats for a property */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    propertyId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Average rating + distribution */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReviewStats"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create review for completed booking (guest) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        bookingId: string;
                        rating: number;
                        comment?: string;
                    };
                };
            };
            responses: {
                /** @description Review created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Review"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete own review or ADMIN moderation */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Review deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** Edit own review */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        rating?: number;
                        comment?: string;
                    };
                };
            };
            responses: {
                /** @description Review updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Review"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/reviews/{id}/reply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Host reply to a review on own property */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        text: string;
                    };
                };
            };
            responses: {
                /** @description Reply saved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Review"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/reviews/{id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report a review for moderation */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        reason: string;
                    };
                };
            };
            responses: {
                /** @description Report submitted */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            reviewId: string;
                            reporterId: string;
                            reason: string;
                            status: components["schemas"]["ReviewReportStatus"];
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        };
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current authenticated user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current user profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CurrentUser"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        /** Soft-delete current user (requires password) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Account deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        options?: never;
        head?: never;
        /** Update current user profile (multipart, optional avatar) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        firstName?: string;
                        lastName?: string;
                        phoneNumber?: string;
                        /** Format: date */
                        dateOfBirth?: string;
                        bio?: string;
                        /** Format: binary */
                        avatar?: string;
                    };
                };
            };
            responses: {
                /** @description Profile updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserProfile"];
                    };
                };
                /** @description Avatar upload accepted, processing in background */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                        };
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
            };
        };
        trace?: never;
    };
    "/users/me/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get aggregated stats for current user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User stats (bookings, properties, reviews counts) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserStats"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove current user avatar */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Avatar removed */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change current user password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        currentPassword: string;
                        newPassword: string;
                        confirmPassword: string;
                    };
                };
            };
            responses: {
                /** @description Password changed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                        };
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/email/request-change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Step 1 — send OTP to new email */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        newEmail: string;
                    };
                };
            };
            responses: {
                /** @description OTP queued to new email */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/email/confirm-change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Step 2 — confirm new email with 6-digit OTP */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        otp: string;
                    };
                };
            };
            responses: {
                /** @description Email updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users (ADMIN only) */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                    role?: "USER" | "ADMIN";
                    dateFrom?: string;
                    dateTo?: string;
                    search?: string;
                    isDeleted?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated user list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                id: string;
                                email: string;
                                firstName: string;
                                lastName: string;
                                avatarUrl: string | null;
                                isDeleted: boolean;
                                isSuspended: boolean;
                                role: components["schemas"]["Role"];
                                /** Format: date-time */
                                createdAt: string;
                            }[];
                            pagination: components["schemas"]["Pagination"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Suspend user account (ADMIN only) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User suspended */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            email: string;
                            firstName: string;
                            lastName: string;
                            isDeleted: boolean;
                            isSuspended: boolean;
                            role: components["schemas"]["Role"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/users/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Restore suspended user (ADMIN only) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User restored */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            email: string;
                            firstName: string;
                            lastName: string;
                            isDeleted: boolean;
                            isSuspended: boolean;
                            role: components["schemas"]["Role"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/users/{id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List reviews across a host's active listings */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated host review list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["HostReview"][];
                            pagination: components["schemas"]["Pagination"];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get public user profile by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Public user profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PublicUserProfile"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
            details?: Record<string, never>;
        };
        Pagination: {
            page?: number;
            limit?: number;
            total?: number;
            totalPages?: number;
        };
        /** @enum {string} */
        Role: "USER" | "ADMIN";
        /** @enum {string} */
        PropertyType: "HOTEL_ROOM" | "APARTMENT" | "HOUSE" | "MEETING_ROOM";
        /** @enum {string} */
        Amenity: "WIFI" | "AIR_CONDITIONING" | "HEATING" | "KITCHEN" | "WASHER" | "DRYER" | "DISHWASHER" | "PARKING" | "POOL" | "GYM" | "BALCONY" | "TERRACE" | "ROOFTOP_TERRACE" | "GARDEN" | "BBQ" | "FIREPLACE" | "BATHTUB" | "PRIVATE_BATHROOM" | "TV" | "SMART_TV" | "COFFEE_MACHINE" | "PROJECTOR" | "STANDING_DESK" | "ELEVATOR" | "PET_FRIENDLY" | "WHEELCHAIR_ACCESSIBLE" | "SEA_VIEW" | "CITY_CENTRE" | "BEACHFRONT" | "KIDS_PLAY_AREA" | "BIKE_INCLUDED" | "BIKE_RENTAL_NEARBY" | "COURTYARD" | "CANAL_VIEW" | "RIVER_VIEW" | "SUN_DECK" | "KAYAK" | "HISTORIC_BUILDING" | "VINYL_RECORD_PLAYER" | "BOOKS" | "SMOKE_ALARM" | "CARBON_MONOXIDE_ALARM";
        /** @enum {string} */
        BookingStatus: "PENDING" | "CONFIRMED" | "CANCELLED" | "COMPLETED";
        /** @enum {string} */
        PayoutStatus: "PENDING" | "READY" | "PAID_OUT" | "CANCELLED";
        /** @enum {string} */
        PaymentStatus: "PENDING" | "SUCCESS" | "REFUND_PROCESSING" | "REFUND_REQUESTED" | "FAILED" | "REFUNDED";
        /** @enum {string} */
        PaymentProvider: "STRIPE";
        /** @enum {string} */
        ReviewReportStatus: "PENDING" | "RESOLVED" | "REJECTED";
        AuthUser: {
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            role: components["schemas"]["Role"];
        };
        AuthResponse: {
            user: components["schemas"]["AuthUser"];
            accessToken: string;
        };
        CurrentUser: {
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            avatarUrl: string | null;
            isSuspended: boolean;
            role: components["schemas"]["Role"];
            /** Format: date-time */
            createdAt: string;
        };
        UserProfile: {
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            avatarUrl: string | null;
            phoneNumber: string | null;
            /** Format: date-time */
            dateOfBirth: string | null;
            bio: string | null;
            role: components["schemas"]["Role"];
        };
        PublicUserProfile: {
            id: string;
            firstName: string;
            lastName: string;
            avatarUrl: string | null;
            bio: string | null;
            /** Format: date-time */
            createdAt: string;
            averageRating: number | null;
            reviewsCount: number;
            listingsCount: number;
        };
        UserStats: {
            completedBookingsCount: number;
            completedNights: number;
            averageRatingAsGuest: number | null;
            averageRatingAsHost: number | null;
            listingsCount: number;
        };
        HostReview: {
            id: string;
            rating: number;
            comment: string | null;
            /** Format: date-time */
            createdAt: string;
            hostReplyText: string | null;
            /** Format: date-time */
            hostReplyCreatedAt: string | null;
            user: {
                firstName: string;
                lastName: string;
                avatarUrl: string | null;
            };
            property: {
                id: string;
                title: string;
            };
        };
        PropertyOwner: {
            id: string;
            firstName: string;
            lastName: string;
            avatarUrl: string | null;
        };
        Property: {
            id: string;
            title: string;
            description: string;
            type: components["schemas"]["PropertyType"];
            city: string;
            country: string;
            district: string | null;
            street: string;
            houseNumber: string | null;
            apartment: string | null;
            latitude: number | null;
            longitude: number | null;
            images: string[];
            /** @description Decimal serialized as string */
            pricePerNight: string;
            maxGuests: number;
            petsAllowed: boolean;
            infantsAllowed: boolean;
            /** @example 15:00 */
            checkInTime: string | null;
            /** @example 11:00 */
            checkOutTime: string | null;
            amenities: components["schemas"]["Amenity"][];
            /** @description Decimal serialized as string */
            averageRating: string | null;
            reviewCount: number;
            ownerId: string;
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @description Display fields carry local names; `en` is the English canonical stored on publish. */
        AddressSuggestion: {
            label: string;
            street: string | null;
            houseNumber: string | null;
            district: string | null;
            city: string;
            country: string;
            en: {
                street: string | null;
                district: string | null;
                city: string;
                country: string;
            };
            latitude: number;
            longitude: number;
        };
        PropertyWithOwner: components["schemas"]["Property"] & {
            owner: components["schemas"]["PropertyOwner"];
        };
        PropertyMapMarker: {
            id: string;
            title: string;
            latitude: number;
            longitude: number;
            /** @description Decimal serialized as string */
            pricePerNight: string;
            /** @description Decimal serialized as string */
            averageRating: string | null;
            images: string[];
        };
        PropertyReview: {
            id: string;
            rating: number;
            comment: string | null;
            /** Format: date-time */
            createdAt: string;
            user: {
                firstName: string;
                lastName: string;
            };
            hostReplyText: string | null;
            hostReplyBy: {
                firstName: string;
                lastName: string;
            } | null;
        };
        LocationDistrict: {
            district: string;
            count: number;
        };
        LocationCity: {
            city: string;
            count: number;
            districts: components["schemas"]["LocationDistrict"][];
        };
        LocationCountry: {
            country: string;
            count: number;
            cities: components["schemas"]["LocationCity"][];
        };
        PropertyDetail: components["schemas"]["PropertyWithOwner"] & {
            reviews: components["schemas"]["PropertyReview"][];
        };
        Payment: {
            id: string;
            bookingId: string;
            /** @description Decimal serialized as string */
            amount: string;
            currency: string;
            status: components["schemas"]["PaymentStatus"];
            provider: components["schemas"]["PaymentProvider"];
            transactionId: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        BookingProperty: {
            id: string;
            title: string;
            description: string;
            type: components["schemas"]["PropertyType"];
            city: string;
            district: string | null;
            street: string;
            houseNumber: string | null;
            apartment: string | null;
            images: string[];
            /** @description Decimal serialized as string */
            pricePerNight: string;
            maxGuests: number;
            petsAllowed: boolean;
            infantsAllowed: boolean;
            amenities: components["schemas"]["Amenity"][];
            /** @description Decimal serialized as string */
            averageRating: string | null;
            reviewCount: number;
            ownerId: string;
        };
        Booking: {
            id: string;
            propertyId: string;
            userId: string;
            /** Format: date-time */
            checkIn: string;
            /** Format: date-time */
            checkOut: string;
            guests: number;
            /** @description Decimal serialized as string */
            totalPrice: string;
            status: components["schemas"]["BookingStatus"];
            payoutStatus: components["schemas"]["PayoutStatus"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            actualCheckOutAt: string | null;
        };
        BookingWithProperty: components["schemas"]["Booking"] & {
            property: components["schemas"]["BookingProperty"];
        };
        BookingListItem: components["schemas"]["Booking"] & {
            property: {
                id: string;
                title: string;
                city: string;
                images: string[];
            };
        };
        /** @description Host booking list item. Diverges from a plain BookingWithProperty: property is the narrow {id,title,city,images} projection (same as BookingListItem), and the guest is exposed as `user`, not `guestInfo`. */
        HostBooking: components["schemas"]["Booking"] & {
            property: {
                id: string;
                title: string;
                city: string;
                images: string[];
            };
            user: {
                id: string;
                firstName: string;
                lastName: string;
            };
        };
        BookingPropertyWithOwner: components["schemas"]["BookingProperty"] & {
            owner: components["schemas"]["PropertyOwner"];
        };
        HostContact: {
            phoneNumber: string | null;
            email: string;
        } | null;
        BookingDetail: components["schemas"]["Booking"] & {
            property: components["schemas"]["BookingPropertyWithOwner"];
            payment: components["schemas"]["Payment"] | null;
            hostContact: components["schemas"]["HostContact"] | null;
        };
        Review: {
            id: string;
            bookingId: string;
            userId: string;
            propertyId: string;
            rating: number;
            comment: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            hostReplyText: string | null;
            hostReplyById: string | null;
            /** Format: date-time */
            hostReplyCreatedAt: string | null;
            user: {
                firstName: string;
                lastName: string;
            };
            hostReplyBy: {
                firstName: string;
                lastName: string;
            } | null;
        };
        ReviewStats: {
            averageRating: number | null;
            totalReviews: number;
            breakdown: {
                1?: number;
                2?: number;
                3?: number;
                4?: number;
                5?: number;
            };
            recentTrend: {
                month: string;
                averageRating: number;
                totalReviews: number;
            }[];
        };
        Favorite: {
            id: string;
            userId: string;
            propertyId: string;
            /** Format: date-time */
            createdAt: string;
            property: components["schemas"]["Property"];
        };
        BlockedDates: {
            bookedRanges: {
                /** Format: date-time */
                checkIn: string;
                /** Format: date-time */
                checkOut: string;
            }[];
            blockedRanges: {
                /** Format: date-time */
                startDate: string;
                /** Format: date-time */
                endDate: string;
                reason: string | null;
            }[];
        };
    };
    responses: {
        /** @description Missing or invalid auth token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Insufficient permissions */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Request validation failed */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
