name: Local
variables:
  - name: baseUrl
    value: http://localhost:3000/api/v1
  - name: propertyId
    value: 258ecc52-b944-493d-a305-34e149bad8cc
  - name: propertyId2
    value: bd6bc164-4a09-4cb2-8394-853e5247a186
  - name: testProperty
    value: d2e183ec-27b3-43ce-b9e8-63b74bc3f53c
  - secret: true
    name: jwt_token
  - name: bookingId
    value: cc1ee44e-098e-42f3-8627-a8cff8f30ca3
  - name: bookingId2
    value: 9334d837-4cd1-4cc0-ab6f-fb9492fc4603
  - name: intentId
    value: pi_3TBuI7HHuwVqJHKY1Qios5YV
  - secret: true
    name: sk_test
